[package]
name = "dspcas"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.12"
tokio = {version = "1.43.0", features = ["full"]}
curl = "0.4.47"
futures = "0.3.31"
clap = "4.5.27"
[[bin]]
name = "dspcas"
path = "src/main.rs"
